default_node: &default_node
  platform: centos
  user: billy

before:
  - bundle exec berks install

environments:
  staging: { before: [ echo "Hello World!" ], nodes:  { vm: { host: '192.168.1.15'} } }

  production:
    attributes:
      net: { hostname: prod }
      users:
        - alex
        - simon
      mysql:
        server_port: 3307
    run_list:
      - recipe[git]
      - recipe[postgresql::server]
    nodes:
      db:
        <<: *default_node
        host: db.myapp.com
        attributes:
          net: { hostname: prod-db }
          mysql:
            server_root_password: prodsecret
      www:
        <<: *default_node
        host: www.myapp.com
        attributes:
          net: { hostname: prod-www }
          nginx:
            workers: 4
        run_list: [ 'recipe[varnish]', 'recipe[nginx]' ]
